sudo: required

language: ruby

services:
  - docker

before_install:
- docker-compose build --no-cache 
- docker-compose up -d; sleep 10
- docker-compose ps

script:
- docker exec -ti VoteSJSU-django python manage.py test 

